import './css/style.css'
import { Inter, Oxygen } from 'next/font/google'
import StyleRegistry from './registry'
import Banner from '@/components/banner'

const oxygen = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400','700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${oxygen.className} antialiased bg-white text-gray-900 tracking-tight`}>
        <StyleRegistry>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            {children}
            <Banner />
          </div>
      </StyleRegistry>
      </body>
    </html>
  )
}
