import './css/style.css'
import { Inter } from 'next/font/google'
import StyleRegistry from './registry'
import Banner from '@/components/banner'
import Header from '@/components/Header'
import F from '@/components/f'
// import Feet from '@/components/Feet/index'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// import StyledJsxRegistry from './registry'
 
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html>
//       <body>
//         <StyledJsxRegistry>{children}</StyledJsxRegistry>
//       </body>
//     </html>
//   )
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}>
      <StyleRegistry>
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          {/* <Header /> */}
          {children}
          <Banner />
          {/* <F /> */}
        </div>
      </StyleRegistry>
      </body>
    </html>
  )
}
